name: example
description: example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## ---- common ----
  common:
    path: ../

  ## ---- 3rd part ----
  pull_to_refresh: 2.0.0 # 上拉加载下拉刷新
  video_player: ^2.6.0 # 視頻播放器
  flutter_inappwebview: ^5.7.2+3 # webview
  url_launcher: 6.1.7 # 打开外部链接

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
